### ISSUE TITLE
Primer caso en el país

### ISSUE THREAD

**Issue by asoliverez** [SistemasMapache/Covid19arData#1]
Hola, el primer caso en el país fue el 2 de marzo, no el 5. Un paciente de CABA.

En los datos de JHU figura el 3 y siempre están un día atrasado, así que coincide.

Otra fuente: https://www.infobae.com/coronavirus/2020/03/03/confirmaron-el-primer-caso-de-coronavirus-en-la-argentina/

Gracias por el esfuerzo. Como siempre, conseguir un dato en Argentina es mas dificil que la salida al mar para Bolivia

**Comment by vlasvlasvlas** [comment]
Gracias!! lo actualizamos.
