### ISSUE TITLE
CSV no se actualiza

### ISSUE THREAD

**Issue by epassaro** [SistemasMapache/Covid19arData#17]
Hola!

Veo que el CSV de datos históricos no se actualiza desde noviembre, sin embargo no hay ningún comentario acerca de eso en el README

**Comment by pfunes** [comment]
Me parece que no se actualiza más. Encontraste alguna fuente alternativa, @epassaro ?

**Comment by vlasvlasvlas** [comment]
hola! la tabla entiendo que la venia manteniendo:
juan freire
https://twitter.com/TotinFraire

y @Fedwr 
https://twitter.com/Fedwr
