### ISSUE TITLE
Segundo caso en el pais

### ISSUE THREAD

**Issue by asoliverez** [SistemasMapache/Covid19arData#2]
El segundo caso es del 5, de acuerdo a las notas en el diario, aunque el informe diario de ese sólo da cuenta de un caso.

Fuente: https://www.infobae.com/sociedad/2020/03/05/se-confirmo-el-segundo-caso-de-coronavirus-en-argentina-es-un-hombre-de-23-anos-que-vino-de-italia/

**Comment by vlasvlasvlas** [comment]
corregido.
Gracias!
