### ISSUE TITLE
Mostrar Datos en mapa coroplético

### ISSUE THREAD

**Issue by javiermatias** [SistemasMapache/Covid19arData#3]
Buenas me parece muy interesante el proyecto, me gustaría aportar al proyecto, por ejemplo mostrando los datos en un mapa coroplético, ya realice la parte de la vista, pero estaría bueno ir actualizando con los datos que se van agregando. Acá esta el ejemplo de como se vería,  https://covid19-argentina.herokuapp.com/ , el tema es que estaría bueno que se vaya actualizando a medida que se van agregando nuevos casos.

Mi mail es javierjimenez78@gmail.com

Cualquier cosa me avisan, saludos Javier

**Comment by ezequiel9** [comment]
que decis de este? covid19argentina.com

**Comment by javiermatias** [comment]
Muy Bueno Eze! Te felicito por el laburo! Como haces para que actualize automáticamente?  estaría bueno que lo pongan como Link en el repo, va es una sugerencia!

**Comment by vlasvlasvlas** [comment]
Subo el link al repo! sip es genial, gracias!

**Comment by vlasvlasvlas** [comment]
Ahi revisen el mapa de Ezequiel que esta buenisimo.
Saludos!
