### ISSUE TITLE
Error con el último dato de tests

### ISSUE THREAD

**Issue by emmanueliarussi** [SistemasMapache/Covid19arData#4]
Hay algo mal con los últimos números que se cargaron de los tests correspondientes al día 10/04/2020 en el archivo Covid19arData - historico.csv. La fila 371 dice  que se hicieron un total de 14150 tests, de los cuales 13584 fueron negativos, lo que nos dejaría un total de 566 positivos. Sin embargo, la cantidad de casos confirmados (tot_casosconf) es de 1975 para ese día.

**Comment by vlasvlasvlas** [comment]
Ahi revisamos.
La data de totales y tests sale directamente de los partes informados por Casa Rosada y chequeados por Jorge Aliaga en su spreadsheet diaro:
https://docs.google.com/spreadsheets/d/1M7uDgWSfy6z1MNbC9FP6jTNgvY7XchJ0m-BfW88SKtQ/edit#gid=0

**Comment by vlasvlasvlas** [comment]
Corregido!!
Gracias Emanuel!! :)
