### ISSUE TITLE
Falta de atribución adecuada

### ISSUE THREAD

**Issue by diegokrein** [SistemasMapache/Covid19arData#5]
Hola,

Como colaborador de OpenStreetMap, me complace ver que está
utilizando los datos de OpenStreetMap en su sitio web:

https://covid19-argentina.herokuapp.com/

Sin embargo, noté que el mapa parece carecer del crédito apropiado.
La licencia de OpenStreetMap requiere que dé crédito a OpenStreetMap
y hacer que los usuarios conozcan la licencia de los datos (enlazando
a nuestra página de derechos de autor). Para más información, ver:

https://www.openstreetmap.org/copyright

La correcta atribución ayuda a evitar malentendidos sobre la fuente
del mapa o datos, así como sobre lo que otros pueden hacer con él. Si
necesita ayuda para hacer los cambios o tiene más preguntas, no dude
en preguntarme en respuesta a este correo electrónico, u otros en uno
de los canales de comunicación de OpenStreetMap:

https://wiki.openstreetmap.org/wiki/Contact

Más importante aún, la atribución nos ayuda a difundir sobre
OpenStreetMap y atraer nuevos colaboradores y construir la comunidad.
Esto es muy importante para mejorar la calidad de la base de datos, de
la cual usted y millones de otros dependen.

Se agradecería el acuse de recibo.

Muchas gracias,
Diego Krein

Contacto de la comunidad Argentina de OpenStreetMap:
https://twitter.com/OpenStreetMapAR

**Comment by CarlosBrys** [comment]
Si va a mostar un mapa utilizando los scripts de Leaflet y las teselas de Mapbox, en la función javascript que crea el mapa en su página: "_function crearMapa(datos)_"
la atribución debe ser a los colaboradores que desinteresadamente contribuyeron a construir el mapa que está utilizando, tal como se indica:

```
attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/">OpenStreetMap</a> contributors, ' +
  | '<a href="https://creativecommons.org/licenses/by-sa/2.0/">CC-BY-SA</a>, ' +
  | 'Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
```
 
Y no a un enlace con su nombre propio, tal como está ahora:

`attribution: '<a href="https://www.linkedin.com/in/javier-matias-jimenez/">Jimenez, Javier Matias</a>',`

**Comment by vlasvlasvlas** [comment]
hola, actualmente no estamos haciendo mapas solamente centralizando el dato en formato abierto.
Este mensaje es para Ezequiel que está armando el mapa en base a esta data. Le paso la info asi lo tiene en cuenta.
Su github es https://github.com/ezequiel9
@ezequiel9

**Comment by vlasvlasvlas** [comment]
Diego y Carlos grax por estar atento a las atribuciones en mapas.
Entiendo el esfuerzo que tienen los maperos OSM y de comunidades.
Abz!
Vladi.
:)

**Comment by ezequiel9** [comment]
Mi mapa tiene los correspondientes colaboradores. Ellos hablan del mapa de:

"attribution: '<a
href="https://www.linkedin.com/in/javier-matias-jimenez/">Jimenez,
Javier Matias</a>',  "

Yo no tengo nada que ver con eso.. :)

Por otro lado, gracias por contribuir con open source y que haya cosas como
estas libre de uso!!

Saludos.

**Comment by vlasvlasvlas** [comment]
ah bien, nose entonces de quien es ese otro mapa :) pensé que era una versión anterior del tuya :D
