### ISSUE TITLE
Número de testeos

### ISSUE THREAD

**Issue by ababino** [SistemasMapache/Covid19arData#7]
Hola,
Felicitaciones por el trabajo! Los datos son de muy buena calidad!

Me gustaria también tener datos de número de testeos diarios. Esta informacion es importante para estimar el Rt. Sobre todo si cambia mucho el numero de testeos. En los informes oficiales del ministerios de salud de la nación esta el numero, pero solo en el pdf.

Ojala puedan agregar esta información.

Gracias!

**Comment by vlasvlasvlas** [comment]
lo sumamos! gracias!

**Comment by ababino** [comment]
Espectacular! Ya use estos nuevos datos [acá](https://github.com/ababino/covid-19).

Gracias!

**Comment by vlasvlasvlas** [comment]
gracias! te sumamos en el listado de reutilizadores :)
