### ISSUE TITLE
Aparecen los nuevos casos confirmados con punto flotante

### ISSUE THREAD

**Issue by floreealonso** [SistemasMapache/Covid19arData#8]
Buen día! Reporto pequeño bug

Muy buen aporte para hacer disponibles los datos de casos en argentina!
Estábamos usando su base de datos para un proyecto social que brinda información del covid.
https://asistocovid.com.ar/#/

Hace unos días los campos "nue_casosconf_diff" y "dia_cuarentena_dnu26" comenzaron a aparecer con punto flotante. También se filtró un NaN del web scraping
![Captura de pantalla de 2020-06-25 11-25-24](https://user-images.githubusercontent.com/64852266/85738894-c1dd8c00-b6d6-11ea-80a8-c17d85fe6c7f.png)

Al momento puedo seguir mostrando bien los datos en el asistente con :
`df[['nue_casosconf_diff','nue_fallecidos_diff']].fillna(value=0).astype(int)`

Gracias por leer!

**Comment by vlasvlasvlas** [comment]
Perdon x el lag, estuve con unas cosas, ya lo reviso. gracias!

**Comment by vlasvlasvlas** [comment]
ahi quedó solucionado, fijate si estaría ok. gracias!

**Comment by floreealonso** [comment]
Quedó bien! Gracias!!

**Comment by vlasvlasvlas** [comment]
genial! grax
